### PR TITLE
Fix git2 diff renames.  Resolves #62

### LINKED ISSUE #62: AssertionError thrown when generating
Every time I try to generate the code debt it throws an assertion error
```
$ git-code-debt-create-tables database.db
$ git-code-debt-generate git@github.com:LibraryOfCongress/bagit-java.git database.db
Cloning into '/var/folders/bl/xmfqp4yx4z1607wydb19x0dc0000gn/T/tmpcYxf4wtemp-repo'...
remote: Counting objects: 26904, done.
remote: Total 26904 (delta 0), reused 0 (delta 0), pack-reused 26904
Receiving objects: 100% (26904/26904), 145.16 MiB | 10.22 MiB/s, done.
Resolving deltas: 100% (11730/11730), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/local/bin/git-code-debt-generate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 180, in main
    args.skip_default_metrics,
  File "/usr/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 97, in load_data
    commits, pool.imap(_get_metrics_inner, mp_args),
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
AssertionError
```

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

File: latest-git.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env bash
+# This is a script used in travis-ci to have latest git
+set -ex
+git clone git://github.com/git/git --depth 1 /tmp/git
+pushd /tmp/git
+make -j 8
+popd
```
Comment (asottile) [inline latest-git.sh]: This (along with the .travis.yml stuf) is lifted directly from https://github.com/pre-commit/pre-commit/blob/60cc4158ed4b4169693b99f70283b18cb25eea63/latest-git.sh
